### ISSUE TITLE
iPhone code can be simplified.

### ISSUE THREAD

**Issue by ghost** [thomasuster/extension-secureRandom#2]
The iPhone code can be simplified to something like:

```
int _getSecureRandom32()
{
    uint32_t value;
    if (SecRandomCopyBytes(kSecRandomDefault,
                sizeof(value), (uint8_t*)&value)) {
        perror("randgetter");
        exit(-1);
    }
    return (int)value;
}
```

[SecRandomCopyBytes](https://developer.apple.com/library/ios/documentation/Security/Reference/RandomizationReference/#//apple_ref/c/func/SecRandomCopyBytes) is part of the `Security` framework.

**Comment by thomasuster** [comment]
Would you submit a PR?
- Please test sizeof(value) always returns 32 or hardcode it
- Please add (SecRandomCopyBytes(...) != 0) in the conditional
- Please do some smoke testing

**Comment by ghost** [comment]
> Would you submit a PR?

Sorry, I'm not actually a Haxe developer.

I came across this code randomly & wanted to let you know about `SecRandomCopyBytes`.

Also: If the random data is for a v4 UUID, why not call [`uuid_generate_random`](https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man3/uuid_generate.3.html) & [`uuid_unparse`](https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man3/uuid_unparse.3.html#//apple_ref/doc/man/3/uuid_unparse)?

I apologize if I've wasted your time!

**Comment by thomasuster** [comment]
You have not wasted my time @ghost. Thank you for sharing information. I needed to find an equivalent API on android, so I happened to fall on this. I'll look at your info and try to clean things up when I can.
